const Style = {
    reviewComponent: {
        width: '60vw',
        paddingLeft: '80px',
        top: '100px',
        margin: '40px',
        fontFamily: 'Roboto Thin, sans-serif',
    },
    summaryReviewStyling: {
        display: 'flex',
        flexDirection: 'row',
        height: '80px',
        borderBottom: '1px solid #c1bdbe',
        borderTop: '1px solid #c1bdbe',
        paddingTop: '30px',
        position: 'relative',
        width: "100%",
    },
    summaryReviewTextRatingStyling: {
        boxSizing: 'border-box',
        display: 'flex',
        textSizeAdjustment: '100%',
        verticalAlign: 'bottom',
        fontSize: '17px',
        fontWeight: 300,
        lineHeight: '22px',
        width: "50%",
    },
    summaryReviewTextStyling: {
        color: '#484848',
        boxSizing: 'border-box',
        letterSpacing: '-0.6px',
        lineHeight: '30px',
        textSizeAdjustment: '100%',
        wordWrap: 'break-word',
        fontWeight: 700,
        fontSize: '25px',
        paddingRight: '10px',
        width: '150px',
    },

    summaryReviewSearchBarInputDiv: {
        display: 'flex',
        flexDirection: 'row',
        position: 'absolute',
        right: '10px',
        width: '230px',
    },
    summaryReviewSearchBarInput: {
        backgroundColor: 'transparent',
        width: '200px',
        fontSize: '15px',
        lineHeight: '18px',
        letterSpacing: '0.2px',
        color: '#484848',
        fontWeight: 'normal',
        padding: '7px 20px',
    },
    summaryReviewSearchBarInputLabel: {
        width: '20px',
        paddingTop: '10px'
    },
    categoryRatingStyling: {
        display: 'flex',
        flexDirection: 'row',
        paddingTop: '20px',
        paddingBottom: '20px',
    },
    categoryRatingLeft: {
        flex: 0.5,
    },
    categoryRatingRight: {
        flex: 0.5,
    },
    categoryRatingItem: {
        display: 'flex',
        flexDirection: 'row',
        padding: '3px',
    },
    categoryRatingItemLabel: {
        width: 150,
    },
    categoryRatingItemRating: {
        width: 200,
    },
    reviewItemContainer: {
        borderBottom: '1px solid #c1bdbe',
        paddingTop: '20px',
        paddingBottom: '20px',
        display: 'flex',
        flexDirection: 'column',
    } ,
    userDetailsContainer: {
        display: "flex",
        flexDirection: "row",
        height: '60px',
        paddingBottom: '20px',
    },
    profilePicStyle: {
        borderRadius : '50%',
        width: '44px',
        height: '44px',
        margin: '5px',
        backgroundColor: 'rgb(216, 216, 216)',
        cursor: 'pointer',
        borderWidth: '2px',
        borderStyle: 'solid',
        borderColor: 'rgb(255, 255, 255)',
    },
    nameContainer: {
        paddingLeft: '10px',
    },
    reviewTextContainer: {
        color: '#484848',
        boxSizing: 'border-box',
        direction: 'ltr',
        display: 'block',
        letterSpacing: '0.2px',
        lineHeight: '22px',
        textSizeAdjust: '100%',
        unicodeBidi: 'isolate',
        fontWeight: 300,
        fontSize: '17px', 
        letterSpacing: '-0.3px',   
    },
    nameStyle: {
        color: '#484848',
        boxSizing: 'border-box',
        letterSpacing: '0.2px',
        lineHeight: '22px',
        textSizeAdjustment: '100%',
        wordWrap: 'break-word',
        fontWeight: 400,
        fontSize: '17px',
        paddingRight: '10px',
    },
    dateStyle: {
        color: '#484848',
        boxSizing: 'border-box',
        letterSpacing: '0.2px',
        lineHeight: '18px',
        textSizeAdjustment: '100%',
        wordWrap: 'break-word',
        fontWeight: 100,
        fontSize: '15px',
        paddingRight: '10px',
    },
    pageIndexStyling: {
        display: 'flex', 
        paddingTop: '10px',
    },
    pageNumberStyling: {
        color: '#008489',
    },
    pageItemStyling: {
        borderRadius: '2px',
        borderWidth: '1px',
        padding: '5px, 10px',
        marginLeft: '10px',
        textAlign: 'left',
    }
}
export default Style;